### ISSUE TITLE
Assign the issue to a hunter when creating PR

### ISSUE THREAD

**Issue by PhantomCracker** [ubiquity/devpool-directory#979]
Today I have found out that when creating a new pull request, the bot does not assign the issue to the hunter until he will not "/start" or "/assign".

Maybe we should create a behaviour that when the hunter create a PR and link the ticket, it will automatically assign the ticket to it. 

<img width="1009" alt="Screenshot 2023-11-05 at 14 52 03" src="https://github.com/ubiquity/devpool-directory/assets/5438246/22b856b6-6884-4cb5-b4de-c16802ed086f">

**Comment by PhantomCracker** [comment]
Why closed?

**Comment by PhantomCracker** [comment]
@pavlovcik ?

**Comment by gitcoindev** [comment]
@PhantomCracker all bot bounties were halted two weeks ago, see https://github.com/ubiquity/ubiquibot/commit/2a7d379db8e87272988766ab09a96c0c86afa10c

**Comment by PhantomCracker** [comment]
Maybe we should have some managers that check the bounties and filter them?

**Comment by pavlovcik** [comment]
> @PhantomCracker all bot bounties were halted two weeks ago, see https://github.com/ubiquity/ubiquibot/commit/2a7d379db8e87272988766ab09a96c0c86afa10c

This should only be for the ubiquibot repository. The other repositories should be fine. 

Also as per the readme of this current repository, these are only supposed to serve as pointers to the tasks. Commands like start and stop should not work in this repository. Instead the user should proceed to the linked repository to work on the task.

**Comment by gitcoindev** [comment]
> > @PhantomCracker all bot bounties were halted two weeks ago, see [ubiquity/ubiquibot@2a7d379](https://github.com/ubiquity/ubiquibot/commit/2a7d379db8e87272988766ab09a96c0c86afa10c)
> 
> This should only be for the ubiquibot repository. The other repositories should be fine.
> 
> Also as per the readme of this current repository, these are only supposed to serve as pointers to the tasks. Commands like start and stop should not work in this repository. Instead the user should proceed to the linked repository to work on the task.
> 
> Lastly, no issues should be filed in the directory. Instead they should be filed in the correct repository. In this case, the ubiquibot repository.

Indeed! I thought the issue targeted bot repository. This repository aggregates all devpool issues with pointers to other repos.

**Comment by pavlovcik** [comment]
Also I just saw the originally linked pull request. 


The bot automatically assigns the associated issue. It is disabled because assignment is disabled on that repository.

**Comment by PhantomCracker** [comment]
Ok, I see, thank you for the information. So if I will find an issue that is not on the bot, I can create a bug on that specific repository and not on the devpool.
